#!/usr/bin/env python3
"""
pipeline/ai_triage_engine.py
─────────────────────────────────────────────────────────────────────────────
AI-powered triage engine for DevSecOps pipeline.

Analyzes every finding in full_report.json using:
  • Groq API (llama-3.3-70b-versatile)  — when GROQ_API_KEY is set
  • Offline mock responses               — when GROQ_API_KEY is absent

Output: mock-data/full_report_triaged.json

Usage:
  export GROQ_API_KEY="gsk_..."
  python3 ai_triage_engine.py

  # Offline / demo mode (no API key needed):
  python3 ai_triage_engine.py

stdlib only – no pip install required.
"""

import json
import os
import sys
import time
import urllib.request
import urllib.error
from copy import deepcopy
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional

# ─────────────────────────────────────────────────────────────
# Paths
# ─────────────────────────────────────────────────────────────
SCRIPT_DIR      = Path(__file__).parent.resolve()
ROOT_DIR        = SCRIPT_DIR.parent
MOCK_DIR        = ROOT_DIR / "mock-data"
REPORT_FILE     = Path(os.environ.get("CONSOLIDATED_REPORT", MOCK_DIR / "full_report.json"))
MOCK_AI_FILE    = Path(os.environ.get("MOCK_AI_FILE", MOCK_DIR / "ai_mock_responses.json"))
OUTPUT_FILE     = Path(os.environ.get("TRIAGED_REPORT", MOCK_DIR / "full_report_triaged.json"))

# ─────────────────────────────────────────────────────────────
# Groq API config
# ─────────────────────────────────────────────────────────────
GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")
GROQ_URL     = "https://api.groq.com/openai/v1/chat/completions"
GROQ_MODEL   = "llama-3.3-70b-versatile" # Stable production model
GROQ_TIMEOUT = 30   # seconds per request
GROQ_DELAY   = 0.8  # seconds between requests (rate limit safety)

# ─────────────────────────────────────────────────────────────
# SLA policy (hours from now)
# ─────────────────────────────────────────────────────────────
SLA_HOURS = {
    "CRITICAL": 24,
    "HIGH":     120,
    "MEDIUM":   336,
    "LOW":      720,
}

# ─────────────────────────────────────────────────────────────
# ANSI colors
# ─────────────────────────────────────────────────────────────
GREEN  = "\033[92m"
YELLOW = "\033[93m"
RED    = "\033[91m"
CYAN   = "\033[96m"
BOLD   = "\033[1m"
DIM    = "\033[2m"
RESET  = "\033[0m"

def c(text: str, *codes: str) -> str:
    return "".join(codes) + str(text) + RESET

# ─────────────────────────────────────────────────────────────
# Prompts
# ─────────────────────────────────────────────────────────────
SYSTEM_PROMPT = (
    "You are an Elite DevSecOps AI Copilot at an enterprise company. "
    "Your objective is to review findings generated by our Quad-Core scanner (Semgrep, Trivy, Checkov, Gitleaks) "
    "and perform highly-accurate Auto-Remediation.\n"
    "You must provide:\n"
    "1. Classification: True Positive / False Positive / Needs Review\n"
    "2. Confidence score (0-100)\n"
    "3. Contextual analysis (WHY this vulnerability matters in production)\n"
    "4. Specific Auto-Remediation code fix. Under 'before' put the vulnerable snippet. Under 'after' put the EXACT replacement code ready for copy/pasting. Do not use placeholders.\n"
    "5. Business impact in 1 concise sentence.\n"
    "Respond ONLY in valid JSON format. Do not use markdown blocks outside the JSON."
)

def get_code_context(filepath: str, line_no: int, window: int = 10) -> str:
    """Reads surrounding code lines for better AI context."""
    path = Path(filepath)
    if not path.exists():
        # Try relative to root if absolute path fails (common in CI)
        path = ROOT_DIR / filepath
        if not path.exists():
            return ""

    try:
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        start = max(0, line_no - window - 1)
        end   = min(len(lines), line_no + window)

        context = []
        for i in range(start, end):
            prefix = ">> " if i + 1 == line_no else "   "
            context.append(f"{i+1:4d} {prefix}{lines[i]}")

        return "\n".join(context)
    except Exception:
        return ""

def build_user_prompt(finding: dict, context: str = "") -> str:
    epss_prob = finding.get('epss_score', 0) * 100
    epss_pct  = finding.get('epss_percentile', 0) * 100

    context_block = f"\nSurrounding Code Context:\n---\n{context}\n---\n" if context else ""

    return (
        f"Finding: {finding.get('title', 'N/A')}\n"
        f"Severity: {finding.get('severity', 'N/A')}\n"
        f"CVSS v3: {finding.get('cvss_v3', 'N/A')}\n"
        f"EPSS Exploit Probability: {epss_prob:.2f}%\n"
        f"EPSS Percentile: {epss_pct:.2f}%\n"
        f"File: {finding.get('affected_file', finding.get('affected_url', 'N/A'))}"
        f":{finding.get('affected_line', '')}\n"
        f"Code snippet: {finding.get('code_snippet', finding.get('attack_payload', 'N/A'))}\n"
        f"{context_block}"
        f"OWASP: {finding.get('owasp_2025', finding.get('owasp_2021', 'N/A'))}\n"
        f"MITRE ATT&CK: {finding.get('mitre_attack', {}).get('technique_id', 'N/A')} "
        f"- {finding.get('mitre_attack', {}).get('technique', 'N/A')}\n\n"
        "Respond with this exact JSON structure:\n"
        "{\n"
        '  "classification": "True Positive|False Positive|Needs Review",\n'
        '  "confidence": 0-100,\n'
        '  "reasoning": "2-3 sentences explaining classification (reference EPSS if low probability)",\n'
        '  "code_fix": {\n'
        '    "before": "vulnerable code",\n'
        '    "after": "fixed code",\n'
        '    "explanation": "why this fix works"\n'
        "  },\n"
        '  "business_impact": "Explain how this specific vulnerability impacts the '+finding.get('app_name', 'target application')+' business logic",\n'
        '  "priority_score": 1-10\n'
        "}"
    )

# ─────────────────────────────────────────────────────────────
# Mock response lookup
# Maps finding rule_id / CVE / pluginid → mock response key
# ─────────────────────────────────────────────────────────────
MOCK_KEY_MAP: dict[str, str] = {
    # SAST
    "javascript.express.security.audit.sqli":     "javascript.express.security.audit.sqli",
    "generic.secrets.security.detected-generic-secret": "generic.secrets.security.detected-generic-secret",
    "javascript.lang.security.audit.path-traversal":    "javascript.lang.security.audit.path-traversal",
    # SCA
    "CVE-2021-44228": "CVE-2021-44228",
    "CVE-2021-23337": "CVE-2021-23337",
    "CVE-2022-0155":  "CVE-2022-0155",
    # IaC
    "CKV_DOCKER_2": "CKV_DOCKER_2",
    "CKV_DOCKER_7": "CKV_DOCKER_7",
    "CKV_DOCKER_1": "CKV_DOCKER_1",
    # DAST
    "40012": "40012",
    "10011": "10011",
}

def resolve_mock_key(finding: dict) -> Optional[str]:
    rule_id = finding.get("rule_id", "")
    return MOCK_KEY_MAP.get(rule_id)

# ─────────────────────────────────────────────────────────────
# Groq API caller
# ─────────────────────────────────────────────────────────────

def call_groq(finding: dict, context: str = "") -> Optional[dict]:
    """
    Call Groq API and return parsed JSON response dict.
    Returns None on any error.
    """
    payload = json.dumps({
        "model": GROQ_MODEL,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": build_user_prompt(finding, context)},
        ],
        "temperature":  0.3,
        "max_tokens":   2048,
        "response_format": {"type": "json_object"},
    }).encode("utf-8")

    req = urllib.request.Request(
        GROQ_URL,
        data=payload,
        headers={
            "Content-Type":  "application/json",
            "Authorization": f"Bearer {GROQ_API_KEY}",
            "User-Agent":    "Mozilla/5.0 (AegisFlow DevSecOps AI Copilot)",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=GROQ_TIMEOUT) as resp:
            body = resp.read().decode("utf-8")
    except urllib.error.HTTPError as exc:
        err_body = exc.read().decode("utf-8", errors="replace")[:300]
        print(c(f"\n    [API ERROR] HTTP {exc.code}: {err_body}", RED), file=sys.stderr)
        return None
    except urllib.error.URLError as exc:
        print(c(f"\n    [API ERROR] Connection failed: {exc.reason}", RED), file=sys.stderr)
        return None
    except Exception as exc:
        print(c(f"\n    [API ERROR] Unexpected: {exc}", RED), file=sys.stderr)
        return None

    try:
        groq_resp = json.loads(body)
        content   = groq_resp["choices"][0]["message"]["content"]
        # Strip potential markdown fences defensively
        content   = content.strip()
        if content.startswith("```"):
            content = content.split("```")[1]
            if content.startswith("json"):
                content = content[4:]
        return json.loads(content)
    except (KeyError, IndexError, json.JSONDecodeError) as exc:
        print(c(f"\n    [PARSE ERROR] Could not parse Groq response: {exc}", RED), file=sys.stderr)
        return None

# ─────────────────────────────────────────────────────────────
# Default fallback (when mock key not found)
# ─────────────────────────────────────────────────────────────

def default_mock(finding: dict) -> dict:
    sev   = finding.get("severity", "MEDIUM")
    title = finding.get("title", "Unknown finding")
    confidence_map = {"CRITICAL": 90, "HIGH": 80, "MEDIUM": 70, "LOW": 60}
    return {
        "classification": "True Positive",
        "confidence":     confidence_map.get(sev, 70),
        "reasoning":      (
            f"Static analysis indicates this {sev.lower()}-severity finding "
            f"({title[:60]}) is likely exploitable based on code context. "
            "Manual verification is recommended to confirm the code path is reachable "
            "and no compensating control exists upstream in the request pipeline."
        ),
        "code_fix": {
            "before":      finding.get("code_snippet", "See finding details."),
            "after":       "Refer to remediation_hint field for fix guidance.",
            "explanation": finding.get("remediation_hint", "Apply security best practices for this vulnerability class."),
        },
        "business_impact": finding.get("business_impact", "Security risk — see finding details."),
        "priority_score":  {"CRITICAL": 9, "HIGH": 7, "MEDIUM": 5, "LOW": 2}.get(sev, 5),
    }

# ─────────────────────────────────────────────────────────────
# SLA deadline calculator
# ─────────────────────────────────────────────────────────────

def compute_sla_deadline(severity: str, now: datetime) -> str:
    hours = SLA_HOURS.get(severity, 168)
    deadline = now + timedelta(hours=hours)
    return deadline.strftime("%Y-%m-%dT%H:%M:%SZ")

# ─────────────────────────────────────────────────────────────
# Classification color
# ─────────────────────────────────────────────────────────────

def classification_color(cls: str) -> str:
    mapping = {
        "True Positive":  (RED,    "🔴 True Positive"),
        "False Positive": (GREEN,  "✅ False Positive"),
        "Needs Review":   (YELLOW, "🔶 Needs Review"),
    }
    color, label = mapping.get(cls, (DIM, cls))
    return c(label, color)

def triage_finding(finding: dict, target_path: str, mode: str):
    """Worker function for parallel triage"""
    now = datetime.now(timezone.utc)
    severity = finding.get("severity", "MEDIUM")

    # ── Get AI Context ──────────────────────────────────
    file_path = finding.get("affected_file", "")
    line_num = finding.get("affected_line", 0)
    context = get_code_context(target_path, file_path, line_num)
    finding["code_context"] = context

    # ── Get AI response ───────────────────────────────────
    ai_resp = None
    if mode == "LIVE":
        ai_resp = call_groq(finding, context)
        if not ai_resp:
             # Fallback
             mock_key = resolve_mock_key(finding)
             ai_resp = default_mock(finding)
    else:
        mock_key = resolve_mock_key(finding)
        ai_resp = default_mock(finding)

    # ── Apply results ───────────────────────────────────
    classification = ai_resp.get("classification", "Needs Review")
    finding["ai_analysis"] = f"[{classification}] {ai_resp.get('reasoning', '')}"
    finding["ai_fix"] = ai_resp.get("code_fix", {})
    finding["ai_confidence"] = ai_resp.get("confidence", 70)
    finding["ai_priority_score"] = ai_resp.get("priority_score", 5)
    finding["business_impact"] = ai_resp.get("business_impact", "")
    finding["status"] = "PENDING_HUMAN_VERIFY"
    finding["ai_model"] = GROQ_MODEL if mode == "LIVE" else f"mock:{GROQ_MODEL}"
    finding["ai_analyzed_at"] = now.strftime("%Y-%m-%dT%H:%M:%SZ")

    # Simple console output
    print(f"  [TRIAGED] {finding.get('id')} -> {classification}")

# ─────────────────────────────────────────────────────────────
# Main triage loop
# ─────────────────────────────────────────────────────────────

def main() -> None:
    print()
    print(c("═" * 64, BOLD))
    print(c("  AI Triage Engine  –  Security Finding Analysis", BOLD, CYAN))
    print(c(f"  Model: {GROQ_MODEL}", DIM))
    print(c("═" * 64, BOLD))
    print()

    # ── Determine mode ────────────────────────────────────────
    if GROQ_API_KEY:
        mode = "LIVE"
        print(c("  Mode: ", BOLD) + c("LIVE — Groq API", GREEN, BOLD))
        print(c(f"  Key:  ...{GROQ_API_KEY[-6:]}", DIM))
    else:
        mode = "MOCK"
        print(c("  Mode: ", BOLD) + c("OFFLINE — using ai_mock_responses.json", YELLOW, BOLD))

    # ── Load full_report.json ─────────────────────────────────
    if not REPORT_FILE.exists():
        print(c(f"  [ERROR] Not found: {REPORT_FILE}", RED), file=sys.stderr)
        sys.exit(1)

    try:
        text = REPORT_FILE.read_text(encoding="utf-8-sig")
        report = json.loads(text)
    except Exception as exc:
        print(c(f"  [ERROR] Failed to load report: {exc}", RED))
        sys.exit(1)

    findings = report.get("findings", [])
    if not findings:
        print(c("  [WARN] No findings to analyze.", YELLOW))
        return

    # ── Determine target_path from args ────────────────────────
    target_path = sys.argv[1] if len(sys.argv) > 1 else "."

    # [SPEED UP] Use Multi-threading for AI Triage
    from concurrent.futures import ThreadPoolExecutor

    print(f"  Analyzing {len(findings)} findings using {GROQ_MODEL} (Parallel Mode)...")
    print("  " + "─" * 60)

    # [REAL IMPACT MODE] Slower but high quality
    with ThreadPoolExecutor(max_workers=3) as executor:
        executor.map(lambda f: triage_finding(f, target_path, mode), findings)

    # Save the triaged report
    REPORT_FILE.write_text(json.dumps(report, indent=4), encoding="utf-8")
    print(f"\n  ✅ Analysis complete. Results saved to {REPORT_FILE.name}")
    print(c("═" * 64, BOLD))

if __name__ == "__main__":
    main()
    elapsed = round(time.time() - start_time, 1)
    print()
    print(c("  ─" * 32, DIM))
    print(c("  Triage Summary", BOLD))
    print(c("  ─" * 32, DIM))

    tp  = stats.get("True Positive", 0)
    fp  = stats.get("False Positive", 0)
    nr  = stats.get("Needs Review", 0)
    err = stats.get("error", 0)

    bar_tp = "█" * tp
    bar_fp = "█" * fp
    bar_nr = "█" * nr

    print(f"    {c('True Positive ', RED)}{tp:>3}  {c(bar_tp, RED)}")
    print(f"    {c('Needs Review  ', YELLOW)}{nr:>3}  {c(bar_nr, YELLOW)}")
    print(f"    {c('False Positive', GREEN)}{fp:>3}  {c(bar_fp, GREEN)}")
    if err:
        print(f"    {c('Parse Errors  ', DIM)}{err:>3}")

    print()
    print(f"    Mode     : {c('Groq API (live)', GREEN) if mode == 'LIVE' else c('Offline mock', YELLOW)}")
    if mode == "LIVE":
        print(f"    API calls: {groq_calls} Groq  /  {mock_calls} mock fallback")
    print(f"    Duration : {elapsed}s  ({total} findings)")
    print()
    print(f"  {c('✓ Triage complete.', GREEN, BOLD)} Report: {c(str(OUTPUT_FILE.relative_to(ROOT_DIR)), CYAN)}")
    print()

    # ── SLA warnings ─────────────────────────────────────────
    critical_tp = [f for f in triaged["findings"]
                   if f.get("severity") == "CRITICAL"
                   and "True Positive" in f.get("ai_analysis", "")]
    if critical_tp:
        print(c(f"  ⚠  {len(critical_tp)} CRITICAL True Positive finding(s) — SLA: 24 hours", RED, BOLD))
        for f in critical_tp:
            print(c(f"     [{f['id']}] {f['title'][:55]}", DIM))
            print(c(f"            Deadline: {f['sla_deadline']}", DIM))
        print()

    print(c("  Open Dashboard to review and assign findings:", DIM))
    print(c("  http://localhost:58080", CYAN))
    print()


if __name__ == "__main__":
    main()
